Yet another project base
roguepygame/roguepygame pull request #10
Opened 2022-12-02 13:53 UTC by MightyJosip

2022-12-02 16:30 UTC, Yvant2000 approved these changes
Pretty solid base !

2022-12-27 16:34 UTC, Matiiss requested changes
A couple of changes should be made, mainly regarding redundancy in arguments to `super` and getting object manager possibly too often.

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/root.py
> +        self.child_objects[str(child_name)] = child_obj
Maybe just use child object as the key?

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/root.py
> +        super(DrawableObject, self).__init__()
Redundant arguments to `super`, just `super().__init__()`

Also if arguments are optional I'm pretty sure it's type hinted like `pygame.Surface | None`, same for `pygame.Rect | None` or use `typing.Optional`

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/root.py
> +        screen.blit(self.image, self.rect)
Must check if `self.image is not None` and `self.rect is not None`, otherwise don't allow optional arguments for those attributes

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/root.py
> +        super(ClickableObject, self).__init__()
Again redundant arguments for `super`

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/root.py
> +            mouse_position = self.program.get_scene().state['mouse_pos']
Most mouse events including this one have a `pos` attribute, so use that, this line is redundant

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/scenes.py
> +        super(MainMenu, self).__init__(**kwargs)
Redundant arguments to `super`

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/ui.py
> +        super(Text, self).__init__()
redundant args to `super`

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/ui.py
> +        super(Button, self).__init__()
redundant args to `super`

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/ui.py
> +    BUTTON_STATES = {'ACTIVE': 0, 'HOVERED': 1, 'INACTIVE': 2}
Should use enums for this, perhaps create an `enums.py` file and create a `ButtonStates` `enum.Enum`, maybe this can be handled in another PR after this gets merged

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/root.py
> +        self.program.get_object_manager().create_object(self)
If object manager doesn't change during a scene there's no need to call this method every time we need to get it, just create an attribute in `__init__`

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/ui.py
> +        self.create_object()
A bit of a too implicit parent for my liking, especially for UI stuff. But I guess UI can be improved in a different PR then.

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/scenes.py
> +        self.program.get_object_manager().object_update()
As mentioned multiple times, will the manager ever change during a scene?

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/scenes.py
> +        self.program.get_object_manager().object_render(screen)
Even if the manager changes during a scene this method most certainly doesn't have to be called in multiple places for the same instance, update method could just reassign an attribute IF the manager is ever expected to change

2022-12-27 16:34 UTC, Matiiss commented on roguepygame/scenes.py
> +        self.program.get_object_manager().object_render(screen)
`get_object_manager` really does not have to be called this often

2023-01-02 11:45 UTC, MightyJosip commented on roguepygame/assets.py
> +    return image.convert_alpha()
I am not sure what would be the correct way, someone can edit this later

2023-01-02 11:48 UTC, MightyJosip commented on roguepygame/assets.py
> +        self.images_list: dict[str, list[pygame.Surface]] = {}
Changed a bit, but I would like to use list for inside dict because we would like to use indexed images, for button you can have names, but for some animations it is harder, easier if we only keep ordering

2023-01-02 11:50 UTC, MightyJosip commented on roguepygame/constants.py
> +    from game import Game
Without that PyCharm gives me unresolved reference warning for https://github.com/roguepygame/roguepygame/blob/9ae9a3f2fe342062b6ecf49f7a7d70c453fcf2e1/roguepygame/constants.py#L9

And I don't like to see yellow background

2023-01-02 11:51 UTC, MightyJosip commented on roguepygame/constants.py
> +
I keep them together because they are "program constants", but someone can edit them later

2023-01-02 11:53 UTC, MightyJosip commented on roguepygame/root.py
> +        self.child_objects[str(child_name)] = child_obj
I would like this dict to be [str, GameObject] so we can access child without actually having direct reference to it in parent, but rather just by using name

2023-01-02 11:56 UTC, MightyJosip commented on roguepygame/root.py
> +        self.program.get_object_manager().create_object(self)
This is actually used only once, during the creation of the object

2023-01-02 11:57 UTC, MightyJosip commented on roguepygame/assets.py
> +def load_image(image_name: str, transparent_color: pygame.Color=None, alpha: int=None) -> pygame.Surface:
Maybe later we can improve type hints

2023-01-03 22:24 UTC, Yu266426 commented on roguepygame/constants.py
> +IMAGE_FOLDER = os.path.join(FOLDER, 'assets\\images')
Use `os.path.join` for `'assets\\images'` too, otherwise it does not work on mac (and linux too?)

2023-01-03 22:26 UTC, Matiiss commented on roguepygame/assets.py
> +def load_image(image_name: str, transparent_color: pygame.Color=None, alpha: int=None) -> pygame.Surface:
"later" is a dangerous place but sure, I guess we first have to lift off the ground

2023-01-03 22:28 UTC, Matiiss commented on roguepygame/assets.py
> +        self.images_list: dict[str, list[pygame.Surface]] = {}
Yeah, lists inside dicts is fine, it's maybe not clear from the example code but those are single item lists there, though we can use differently structure lists too, main thing is that we just have a single data structure for the images, instead of two rather separate ones.

2023-01-03 23:03 UTC, Matiiss requested changes
Some stuff still has to be resolved. Some of it can be passed on to next PRs

2023-01-04 12:21 UTC, MightyJosip commented on roguepygame/root.py
> +        self.program.get_object_manager().remove_object(self)
This method is also called once per object lifetime. And this PR doesn't only have object manager, it also has scene manager, event manager and possibly in the future even more. All of them are easily reachable over the program attribute, and I wouldn't want to overload the game object with attributes not specifically connected to game object

2023-01-04 16:19 UTC, Matiiss approved these changes
LGTM 🎉

2023-01-04 19:16 UTC, ScriptLineStudios commented
Looks good to me!

2023-01-04 19:18 UTC, ScriptLineStudios approved these changes
Looks like a solid base to work off!

2023-01-04 19:26 UTC, merged